"""add notifications

Revision ID: 3e02c8a92134
Revises: a6c9bfa7d195
Create Date: 2026-04-28 20:11:10.596592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e02c8a92134'
down_revision: Union[str, Sequence[str], None] = 'a6c9bfa7d195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workout_id', name='uq_notification_user_workout')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_workout_id'), 'notifications', ['workout_id'], unique=False)
    op.add_column('workouts', sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workouts', sa.Column('notification_task_id', sa.String(length=255), nullable=True))
    op.add_column('workouts', sa.Column('notification_sent', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_workouts_remind_at'), 'workouts', ['remind_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_remind_at'), table_name='workouts')
    op.drop_column('workouts', 'notification_sent')
    op.drop_column('workouts', 'notification_task_id')
    op.drop_column('workouts', 'remind_at')
    op.drop_index(op.f('ix_notifications_workout_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
