"""add media fields to exercises

Revision ID: 86cb489c998d
Revises: 3e02c8a92134
Create Date: 2026-05-26 18:37:51.843311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86cb489c998d'
down_revision: Union[str, Sequence[str], None] = '3e02c8a92134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('exercises', sa.Column('muscle_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'muscle_image_url')
    op.drop_column('exercises', 'video_url')
    # ### end Alembic commands ###
